=== bensz92/tennis/src/main/resources/tennis.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd" />
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tennis_seasons" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tennis_season" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tournament" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="finals" minOccurs="1" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="match" minOccurs="1" maxOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="players" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="player-ref" minOccurs="2" maxOccurs="2">
                                                                                            <xs:complexType>  
                                                                                                <xs:sequence>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute name="id" use="required" type="xs:IDREF"/>
                                                                                            </xs:complexType>                                                                                    
                                                                                        </xs:element>
                                                                                    </xs:sequence>                                                                                
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element name="result" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="set" minOccurs="2" maxOccurs="5"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="semi-finals" minOccurs="1" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="match" minOccurs="2" maxOccurs="2">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="players" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="player-ref" minOccurs="2" maxOccurs="2">
                                                                                            <xs:complexType>  
                                                                                                <xs:sequence>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute name="id" use="required" type="xs:IDREF"/>
                                                                                            </xs:complexType>                                                                                    
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element name="result" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="set" minOccurs="2" maxOccurs="5"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="quarter-finals" minOccurs="1" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="match" minOccurs="4" maxOccurs="4">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="players" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="player-ref" minOccurs="2" maxOccurs="2">
                                                                                            <xs:complexType>  
                                                                                                <xs:sequence>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute name="id" use="required" type="xs:IDREF"/>
                                                                                            </xs:complexType>                                                                                    
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element name="result" minOccurs="1" maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="set" minOccurs="2" maxOccurs="5"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                                <xs:attribute name="type" type="xs:string" use="required"/>
                                                <xs:attribute name="surface" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="year" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="players" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player" minOccurs="2" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="year_of_birth" type="xs:string"/>
                                        <xs:element name="birthplace" type="xs:string"/>
                                        <xs:element name="weight" type="xs:int"/>
                                        <xs:element name="height" type="xs:int"/>
                                        <xs:element name="turnedpro" type="xs:string"/>
                                        <xs:element name="plays" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="player-key">
            <xs:selector xpath="players/player"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
        <xs:keyref refer="player-key" name="player-keyref">
            <xs:selector xpath="match/players/player-ref"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== bensz92/tennis/src/main/resources/tennis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="tennis.xsd" type="application/xml"?>
<root>
    <tennis_seasons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="tennis.xsd">
           <tennis_season year="2015">
            <tournament name="Australian_Open" type="Grand_Slam" surface="Hard">               
                <finals>
                    <match>
                        <players>
                            <player-ref id="Djokovic"/>
                            <player-ref id="Murray"/>
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:7</set>
                            <set>6:3</set>
                            <set>6:0</set>
                        </result>
                    </match>
                </finals>               
                <semi-finals>       
                    <match>
                        <players>         
                            <player-ref id="Djokovic"/>
                            <player-ref id="Wawrinka"/>   
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>3:6</set>
                            <set>6:4</set>
                            <set>4:6</set>
                            <set>6:0</set>
                        </result>
                    </match>                   
                    <match>
                        <players>
                            <player-ref id="Murray"/>
                            <player-ref id="Berdych"/>    
                        </players>
                        <result>
                            <set>6:7</set>
                            <set>6:0</set>
                            <set>6:3</set>
                            <set>7:5</set>
                            <set>6:2</set>
                        </result>
                    </match>                  
                </semi-finals>                
                <quarter-finals>                    
                    <match>
                        <players>
                            <player-ref id="Djokovic"/>
                            <player-ref id="Raonic"/>
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:4</set>
                            <set>6:2</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Berdych"/>
                            <player-ref id="Nadal"/>   
                        </players>
                        <result>
                            <set>6:2</set>
                            <set>6:0</set>
                            <set>7:6</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Wawrinka"/>
                            <player-ref id="Nishikori"/>
                        </players>
                        <result>
                            <set>6:3</set>
                            <set>6:4</set>
                            <set>7:6</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Murray"/>
                            <player-ref id="Kyrgios"/>   
                        </players>
                        <result>
                            <set>6:3</set>
                            <set>7:6</set>
                            <set>6:3</set>
                        </result>
                    </match>                 
                </quarter-finals>
            </tournament>
            <tournament name="Roland_Garros" type="Grand_Slam" surface="Clay">               
                <finals>
                    <match>
                        <players>
                            <player-ref id="Wawrinka"/>
                            <player-ref id="Djokovic"/>
                        </players>
                        <result>
                            <set>4:6</set>
                            <set>6:4</set>
                            <set>6:3</set>
                            <set>6:4</set>
                        </result>
                    </match>
                </finals>               
                <semi-finals>       
                    <match>
                        <players>         
                            <player-ref id="Djokovic"/>
                            <player-ref id="Murray"/>   
                        </players>
                        <result>
                            <set>6:3</set>
                            <set>6:3</set>
                            <set>5:7</set>
                            <set>5:7</set>
                            <set>6:1</set>
                        </result>
                    </match>                   
                    <match>
                        <players>
                            <player-ref id="Wawrinka"/>
                            <player-ref id="Tsonga"/>    
                        </players>
                        <result>
                            <set>6:3</set>
                            <set>6:7</set>
                            <set>7:6</set>
                            <set>6:4</set>
                        </result>
                    </match>                  
                </semi-finals>                
                <quarter-finals>                    
                    <match>
                        <players>
                            <player-ref id="Djokovic"/>
                            <player-ref id="Nadal"/>
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:3</set>
                            <set>6:1</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Wawrinka"/>
                            <player-ref id="Federer"/>   
                        </players>
                        <result>
                            <set>6:4</set>
                            <set>6:3</set>
                            <set>7:6</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Murray"/>
                            <player-ref id="Ferrer"/>
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:2</set>
                            <set>5:7</set>
                            <set>6:1</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Tsonga"/>
                            <player-ref id="Nishikori"/>   
                        </players>
                        <result>
                            <set>6:1</set>
                            <set>6:4</set>
                            <set>4:6</set>
                            <set>3:6</set>
                            <set>6:3</set>
                        </result>
                    </match>                 
                </quarter-finals>
            </tournament>
            
            <tournament name="Wimbledon" type="Grand_Slam" surface="Grass">               
                <finals>
                    <match>
                        <players>
                            <player-ref id="Djokovic"/>
                            <player-ref id="Federer"/>
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:7</set>
                            <set>6:4</set>
                            <set>6:3</set>
                        </result>
                    </match>
                </finals>               
                <semi-finals>       
                    <match>
                        <players>         
                            <player-ref id="Djokovic"/>
                            <player-ref id="Gasquet"/>   
                        </players>
                        <result>
                            <set>7:6</set>
                            <set>6:4</set>
                            <set>6:4</set>
                        </result>
                    </match>                   
                    <match>
                        <players>
                            <player-ref id="Federer"/>
                            <player-ref id="Murray"/>    
                        </players>
                        <result>
                            <set>7:5</set>
                            <set>7:5</set>
                            <set>6:4</set>
                        </result>
                    </match>                  
                </semi-finals>                
                <quarter-finals>                    
                    <match>
                        <players>
                            <player-ref id="Djokovic"/>
                            <player-ref id="Cilic"/>
                        </players>
                        <result>
                            <set>6:4</set>
                            <set>6:4</set>
                            <set>6:4</set>
                        </result>
                    </match>
                    <match>
                        <players>
                            <player-ref id="Federer"/>
